name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v

    - name: Test & publish code coverage to Code Climate
      uses: paambaati/codeclimate-action@v8.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: swift test -v --enable-code-coverage
        debug: true
        coverageLocations: |
          ${{github.workspace}}/.build/debug/codecov/*.json:lcov-json
